column virtualization
karry08/fixed-data-table-2 pull request #1
Opened 2021-07-05 15:03 UTC by karry08

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

2021-07-08 09:50 UTC, pradeepnschrodinger requested changes
Let's remove console.log statements and uncomment temporary changes throughout the whole review.

2021-07-08 09:50 UTC, pradeepnschrodinger commented on examples/ResizeExample.js
> +        //  fixed={true}
uncomment lines

2021-07-08 09:50 UTC, pradeepnschrodinger commented on src/FixedDataTable.js
> +     // console.log(scrollX)
remove console.log statements

2021-07-08 17:30 UTC, karry08 commented on src/FixedDataTableBufferedRows.js
>        />
Sent the required props for column virtualization

2021-07-08 17:30 UTC, karry08 commented on src/FixedDataTableCell.js
return null if the column is fake/not rendered

2021-07-08 17:30 UTC, karry08 commented on src/FixedDataTableCellGroup.js
> +    var contentWidth = columns.length && (columns[columns.length-1].offset+ columns[columns.length-1].props.width);
TODO calculate content width using interval tree , need to make 3 trees each for fixed,fixed right ,scrollable columns

2021-07-08 17:30 UTC, karry08 commented on src/FixedDataTableRow.js
> +    var fixedRightColumnsWidth = fixedRightColumns.length && (fixedRightColumns[fixedRightColumns.length-1].offset+fixedRightColumns[fixedRightColumns.length-1].props.width);
TODO : can be calculated using interval tree

2021-07-08 17:30 UTC, karry08 commented on src/reducers/computeRenderedCols.js
> +
functions for calculating rendered cols similar to rows

2021-07-08 17:30 UTC, karry08 commented on src/reducers/index.js
>      scrollContentHeight: 0,
col arrays that need to be rendered

2021-07-08 17:30 UTC, karry08 commented on src/reducers/index.js
column props for each column group

2021-07-08 17:30 UTC, karry08 commented on src/reducers/index.js
> +      newState= initializeColWidthsAndOffsets(newState);
for initializing col width and interval tree

2021-07-08 17:30 UTC, karry08 commented on src/reducers/index.js
> +
function to calculate rendered cols

2021-07-08 17:30 UTC, karry08 commented on src/reducers/index.js
> +      const scrollAnchorX=getScrollAnchorX(newState,newProps,oldProps);
scroll anchor state for x scrollbar

2021-07-08 17:30 UTC, karry08 commented on src/reducers/scrollAnchorX.js
> +/**
reducer similar to scroll anchor but for horizontal scroll bar

2021-07-08 17:30 UTC, karry08 commented on src/reducers/updateColWidth.js
> +   const newWidth=storedWidths[colIdx];
TODO needs to be updated

2021-07-08 17:30 UTC, karry08 commented on src/selectors/scrollbarsVisible.js
> +     availableWidth
added one more return value available width

2021-07-08 17:30 UTC, karry08 commented on src/selectors/tableHeights.js
> +     bodyWidth,
added one more return value body width

2021-07-16 08:13 UTC, deshpsuy commented
Can you delete package-lock.json and use yarn instead of npm to prevent creating it.

2021-07-21 08:21 UTC, pradeepnschrodinger requested changes

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTableBufferedRows.js
> +        storedWidths={this.props.storedWidths}
where is `storedWidths` being passed, and where is it used?

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTable.js
> +        //  offsetLeft={offsetLeft}
nit: remove commented out code

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTable.js
> +        fixedColOffsets={this.props.fixedColOffsets}
nit: fix indentation

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTableCell.js
> +    return true;
please fix `shouldComponentUpdate`

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTableCellGroup.js
> +  }
why do we need this?

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTableCellGroup.js
> +      for (let i = 0, j = colsToRender.length; i < j; i++) {
nit: use [for-of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) statement

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTableCellGroup.js
>    getCellGroupWidth = () => {
please leave a TODO to calculate this in the reducer

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTableCellGroup.js
> +    var colsToRender=props.colsToRender || [];
nit: use `let` instead of `var`

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTableCellGroup.js
> +    for (var i = 0, j = colsToRender.length; i < j; i++) {
shouldn't we iterate over `this._staticCells` rather than `colsToRender`?

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTableCellGroup.js
> +    if(!(this.props.columns[idx]))continue;
```suggestion
    if (!this.props.columns[idx]) {
      continue;
    }
```

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTableCellGroup.js
> +    if(!(this.props.columns[idx]))continue;
when is this actually undefined?

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTableCellGroup.js
> +      //currentPosition=this.props.colOffsets[idx];
nit: For consistency with other parts of the codebase, use `colOffsets` rather than `columns[idx].offset`

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTableCellGroup.js
> +      var recyclable =columnProps&& _.get(
when does columnProps not exist?

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTableCellGroup.js
> +          i,idx,
nit: put in new line

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTableCellGroup.js
> +        offsetLeft={this.props.offsetLeft}
unused?

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTableCellGroup.js
> +        <FixedDataTableCellGroupImpl {...props} offsetLeft={this.props.offsetLeft} />
what's the use of `offsetLeft`

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTableRow.js
> +    var fixedColumnsWidth = fixedColumns.length && (fixedColumns[fixedColumns.length-1].offset+fixedColumns[fixedColumns.length-1].props.width);
Aren't we already calculating widths/offsets from the reducer? Let's make use of them here.

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/FixedDataTableStore.js
> + 'use strict';
are the changes in this file required for this review?

2021-07-21 08:21 UTC, pradeepnschrodinger commented on src/plugins/ResizeReorder/ResizeCell.js
> +
nit: remove this change

2021-08-05 01:04 UTC, pradeepnschrodinger requested changes
lgtm once comments are resolved

2021-08-05 01:04 UTC, pradeepnschrodinger commented on src/selectors/columnTemplates.js
> + import forEach from 'lodash/forEach';
remove extra whitespace

2021-08-05 01:04 UTC, pradeepnschrodinger commented on src/reducers/updateColWidth.js
> +  * NOTE (jordan) This alters state so it shouldn't be called
This note isn't completely true anymore cause our immer powered reducers can mutate state. 

Can you readjust the TODO to something like:
`NOTE (karry08): This mutates state`

2021-08-05 01:04 UTC, pradeepnschrodinger commented on src/reducers/scrollAnchorX.js
> + * @providesModule scrollAnchor
Let's call this file the `columnAnchor`, and also rename `scrollAnchorX` to `columnAnchor`

2021-08-05 01:04 UTC, pradeepnschrodinger commented on src/reducers/scrollAnchorX.js
> +     // leads to it not being different from the scrollY specified
nit: change scrollY to scrollX

2021-08-05 01:04 UTC, pradeepnschrodinger commented on src/reducers/updateColWidth.js
> +   if(!state.scrollableColumns.cell[colIdx].props.width){
why do we need this?

2021-08-05 01:04 UTC, pradeepnschrodinger commented on src/reducers/index.js
> +  return {...newState, colSettings:{...newState.colSettings,colsCount:colsCount}}
rename `colSettings` to `columnSettings` and `colsCount` to `columnsCount`

2021-08-05 01:04 UTC, pradeepnschrodinger commented on src/reducers/index.js
> +function initializeColWidthsAndOffsets(state) {
nit: fix spacing

2021-08-05 01:04 UTC, pradeepnschrodinger commented on src/reducers/index.js
> +  let minColumn=-1;
what does this represent? Is it the minimum column width? In that case let's rename it to minColumnWidth

2021-08-05 01:04 UTC, pradeepnschrodinger commented on src/reducers/index.js
> +    { columnGroupProps, columnProps, elementTemplates,colsCount });
why store colsCount inside newState? Shouldn't it be present in newState.columnSettings?

2021-08-05 01:04 UTC, pradeepnschrodinger commented on src/selectors/roughHeights.js
> +   const avgVisibleColCount = Math.ceil(maxAvailableWidth / minColumn) + 1;
Can you explain the logic behind choosing the width of the thinnest column for this calculation?

2021-08-05 01:04 UTC, pradeepnschrodinger commented on src/selectors/roughHeights.js
> +  // const fullRowHeight = rowHeight + subRowHeight;
nit: remove commented out code

2021-08-05 01:04 UTC, pradeepnschrodinger commented on src/selectors/tableHeights.js
> +     bodyWidth,
This actually represents the available width for just the scrollable columns rather than the width of the entire table body, right?
Let's rename it to `scrollableBodyWidth`.

2021-08-05 01:04 UTC, pradeepnschrodinger commented on src/selectors/tableHeights.js
> + function tableHeights(
`tableHeights` also returns the scrollable body width. So maybe this should be called `tableDimensions`?

2021-08-05 01:04 UTC, pradeepnschrodinger commented on src/reducers/computeRenderedCols.js
> + function computeRenderedFixedCols(state,bodyWidth){
please fix formatting

2021-08-05 01:04 UTC, pradeepnschrodinger commented on src/reducers/index.js
> +    fixedContentWidth,
`fixedContentWidth` is simply the sum of `fixedRightColumnsWidth` and `fixedColumnsWidth`, which is a derived quantity. Let's avoid storing it to state

2023-06-30 14:43 UTC, closed without merging